Tracker:AddLocations("locations/Overworld.jsonc")
Tracker:AddLocations("locations/Things Betwixt.jsonc")
Tracker:AddLocations("locations/Majula.jsonc")
Tracker:AddLocations("locations/The Pit.jsonc")
Tracker:AddLocations("locations/Heides Tower of Flame.jsonc")
Tracker:AddLocations("locations/Aldias Keep.jsonc")
Tracker:AddLocations("locations/Belfry Luna.jsonc")
Tracker:AddLocations("locations/Iron Keep.jsonc")
Tracker:AddLocations("locations/Belfry Sol.jsonc")
Tracker:AddLocations("locations/Black Gulch.jsonc")
Tracker:AddLocations("locations/Grave of Saints.jsonc")
Tracker:AddLocations("locations/Cathedral of Blue.jsonc")
Tracker:AddLocations("locations/Sinners Rise.jsonc")
Tracker:AddLocations("locations/Dragon Aerie.jsonc")
Tracker:AddLocations("locations/Dragon Shrine.jsonc")
Tracker:AddLocations("locations/Doors of Pharros.jsonc")
Tracker:AddLocations("locations/Undead Purgatory.jsonc")
Tracker:AddLocations("locations/ThroneOfWant.jsonc")


Tracker:AddLocations("locations/Shaded Woods.jsonc")
Tracker:AddLocations("locations/Forest of Fallen Giants.jsonc")
Tracker:AddLocations("locations/Lost Bastille.jsonc")
Tracker:AddLocations("locations/Huntsmans Copse.jsonc")
Tracker:AddLocations("locations/Harvest Valley.jsonc")
Tracker:AddLocations("locations/Earthen Peak.jsonc")
Tracker:AddLocations("locations/No-Mans Wharf.jsonc")
Tracker:AddLocations("locations/The Gutter.jsonc")
Tracker:AddLocations("locations/Brightstone Cove Tseldora.jsonc")
Tracker:AddLocations("locations/Drangleic Castle.jsonc")
Tracker:AddLocations("locations/Shrine of Amana.jsonc")
Tracker:AddLocations("locations/Undead Crypt.jsonc")
Tracker:AddLocations("locations/Memories.jsonc")


Tracker:AddLocations("locations/Shulva Sanctum City.jsonc")
Tracker:AddLocations("locations/Memory of Old Iron King.jsonc")
Tracker:AddLocations("locations/Iron Passage.jsonc")
Tracker:AddLocations("locations/Brume Tower.jsonc")
Tracker:AddLocations("locations/Cave of the Dead.jsonc")
Tracker:AddLocations("locations/Dragons Sanctum.jsonc")
Tracker:AddLocations("locations/Dragons Rest.jsonc")
Tracker:AddLocations("locations/Frozen Eleum Loyce.jsonc")
Tracker:AddLocations("locations/Frigid Outskirts.jsonc")
Tracker:AddLocations("locations/Grand Cathedral.jsonc")

